project:
  type: website
  output-dir: docs

website:
  title: "XRS's Logs"
  site-url: https://xrsrke.github.io
  navbar:
    right:
      - icon: github
        href: https://github.com/xrsrke
      - icon: twitch
        href: https://twitch.com/xrsrke
      - icon: twitter
        href: https://twitter.com/xariusrke
      - icon: rss
        href: https://xrsrke.github.io/index.xml
format:
  html:
    theme: litera
    css: styles.css



