project:
  type: website
  output-dir: docs

website:
  title: "xrs"
  navbar:
    right:
      - projects.qmd
      - about.qmd
      - icon: twitch
        href: https://twitch.com/xrsrke
      - icon: twitter
        href: https://twitter.com/xrsrke
      - icon: github
        href: https://github.com/xrsrke
format:
  html:
    theme: litera
    css: styles.css



